(function () {
  var root = document.documentElement, sections = [].slice.call(document.querySelectorAll('.section')), links = [].slice.call(document.querySelectorAll('#nav nav a'));
  var control = document.getElementById('page-control'), title = document.getElementById('page-title'), number = document.getElementById('page-number'), progress = document.getElementById('progress');
  var reduce = matchMedia('(prefers-reduced-motion: reduce)').matches, last = -1, ticking = false;
  function revealAll(){ document.querySelectorAll('.reveal').forEach(function(el){ el.classList.add('visible'); }); }
  if (reduce || !('IntersectionObserver' in window)) revealAll();
  else { var observer = new IntersectionObserver(function(entries){ entries.forEach(function(entry){ if(entry.isIntersecting){ entry.target.classList.add('visible'); observer.unobserve(entry.target); } }); }, {threshold:.12,rootMargin:'0px 0px -6% 0px'}); document.querySelectorAll('.reveal').forEach(function(el){ observer.observe(el); }); }
  function current(){ var point = innerHeight*.38, best=0, distance=Infinity; sections.forEach(function(section,index){ var rect=section.getBoundingClientRect(); if(rect.top<=point&&rect.bottom>point){ best=index; distance=-1; } else if(distance!==-1&&Math.abs(rect.top-point)<distance){ best=index; distance=Math.abs(rect.top-point); } }); return best; }
  function paint(){ var index=current(), section=sections[index], height=document.documentElement.scrollHeight-innerHeight; progress.style.width=(height>0?Math.min(100,scrollY/height*100):0)+'%'; root.classList.toggle('dark-nav',section.classList.contains('dark')||section.classList.contains('hero')); control.classList.toggle('is-visible',index>0); title.textContent=section.dataset.title; number.textContent=String(index+1).padStart(2,'0')+' / '+String(sections.length).padStart(2,'0'); links.forEach(function(link){ link.classList.toggle('active',link.dataset.chapter===section.dataset.chapter); }); if(index!==last){ last=index; if(section.id&&history.replaceState) history.replaceState(null,'','#'+section.id); } }
  function go(index){ sections[Math.max(0,Math.min(sections.length-1,index))].scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'}); }
  addEventListener('scroll',function(){ if(!ticking){ requestAnimationFrame(function(){paint();ticking=false;});ticking=true;}},{passive:true}); addEventListener('resize',paint);
  document.getElementById('page-prev').addEventListener('click',function(){go(current()-1);}); document.getElementById('page-next').addEventListener('click',function(){go(current()+1);});
  var toggle=document.getElementById('present-toggle'); toggle.addEventListener('click',function(){ root.classList.toggle('present'); var active=root.classList.contains('present'); toggle.textContent=active?'退出演示':'演示模式'; toggle.setAttribute('aria-pressed',active); });
  addEventListener('keydown',function(event){ if(event.metaKey||event.ctrlKey||event.altKey||/INPUT|TEXTAREA|SELECT/.test(event.target.tagName))return; if(event.key==='p'||event.key==='P'){event.preventDefault();toggle.click();} if(['ArrowDown','ArrowRight','PageDown'].indexOf(event.key)>-1){event.preventDefault();go(current()+1);} if(['ArrowUp','ArrowLeft','PageUp'].indexOf(event.key)>-1){event.preventDefault();go(current()-1);} });
  var filters=[].slice.call(document.querySelectorAll('[data-filter-group] button')), rows=[].slice.call(document.querySelectorAll('#keyword-table [data-platform]')); filters.forEach(function(button){button.addEventListener('click',function(){filters.forEach(function(item){item.classList.toggle('active',item===button);});rows.forEach(function(row){row.hidden=button.dataset.filter!=='all'&&row.dataset.platform!==button.dataset.filter;});});});
  paint();
})();
